sudo: false

language: python
python:
  - pypy

cache:
  pip: true
  directories:
    - env

install:
  - pip install coveralls

before_script:
  - make env
  - make depends

script:
  - make ci

after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
